### PR TITLE
fix(2981): remote join wait on downsream jobs during restart

### LINKED ISSUE #2981: Remote-join job doesn't wait on downstream jobs during restart
**What happened**:

When an upstream job of the remote-join job is restarted, remote-join job immediately runs reusing build status from previous event.

https://cd.screwdriver.cd/pipelines/12907/events/784132
Screenshot 2024-01-11 at 3 33 48 PM

Job first was restarted from previous event, where remote-join in job `second` worked as expected, however in the new event, job `second` ran immediately without waiting for any of the downstream to be triggered or executed. 

**What you expected to happen**:

Job `second` in the restarted event should depend for status from newly triggered remote downstream jobs. 

**How to reproduce it**:

### PR DESCRIPTION
**Pull request by yakanechi**
## Context

fix #2981
When an upstream job of the remote-join job is restarted, remote-join job immediately runs reusing build status from previous event.

## Objective

When a remote join job's upstream jobs are restarted, the remote join job will use the post-restart build status as the trigger for jobs that may run from the restart job.

Enumerate jobs started after the restart job, referring to [the subgraph filter in the UI](https://github.com/screwdriver-cd/ui/blob/8a764ea1a6db38e29e85588a8cc7fcc56d770869/app/utils/graph-tools.js#L454), and do not use the recent build status of the group event.

- About the test
We found another bug related to remote join while working on this. (#3177)
Therefore, a test has been added to the “Tests for behavior not ideal” section
Also, with this fix, the test that was originally in “Tests for behavior not ideal” works as expected so that it will be removed and the test that was xit will be executed.

## References
#2981
#3177

## License
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: plugins/builds/triggers/helpers.js [hunk 1]
```diff
@@ -1032,6 +1033,48 @@ function buildsToRestartFilter(joinPipeline, groupEventBuilds, currentEvent, cur
...
+    if (!startNode || !nodes.length) {
+        return [];
+    }
+
+    let start = startNode;
+
+    // startNode can be a PR job in PR events, so trim PR prefix from node name
+    if (startNode.match(/^PR-[0-9]+:/)) {
+        start = startNode.split(':')[1];
+    }
```
Comment (y-oksaku) [inline plugins/builds/triggers/helpers.js:1056]: You can use these functions.

https://github.com/screwdriver-cd/screwdriver/blob/919680ba9b286704f211adc6caff347e028543c5/plugins/builds/triggers/helpers.js#L362-L364

https://github.com/screwdriver-cd/screwdriver/blob/919680ba9b286704f211adc6caff347e028543c5/plugins/builds/triggers/helpers.js#L371-L377

File: plugins/builds/triggers/helpers.js [hunk 2]
```diff
@@ -1032,6 +1033,48 @@ function buildsToRestartFilter(joinPipeline, groupEventBuilds, currentEvent, cur
...
+
+    const visiting = [start];
+
+    const visited = new Set(visiting);
+
+    if (edges.length) {
+        while (visiting.length) {
+            const cur = visiting.shift();
```
Comment (y-oksaku) [inline plugins/builds/triggers/helpers.js:1064]: `Array.shift` is slower than `Array.pop`.
So using `visiting.pop()` would be better if we can use `pop` method here.

File: plugins/builds/triggers/helpers.js [hunk 3]
```diff
@@ -673,8 +673,8 @@ async function getParallelBuilds({ eventFactory, parentEventId, pipelineId }) {
  * @param {ParentBuilds} parentBuilds parent builds
  * @param {Build[]} relatedBuilds Related builds which is used to fill parentBuilds data
  * @param {Event} currentEvent Current event
- * @param {Event} nextEvent Next triggered event (Remote trigger or Same pipeline event triggered as external)
- * @returns {ParentBuilds} Merged parent builds { "${pipelineId}": { jobs: { "${jobName}": ${buildId} }, eventId: 123 }  }
+ * @param {Event} nextEvent Next triggered event (Remote trigger or Same pipeline event triggered as external) * @returns {ParentBuilds} Merged parent builds { "${pipelineId}": { jobs: { "${jobName}": ${buildId} }, eventId: 123 }  }
+ * @param {string[]} ignoreJobs Names of job that may be run on current event
```
Comment (y-oksaku) [inline plugins/builds/triggers/helpers.js:677]:
```suggestion
 * @param {Event} nextEvent Next triggered event (Remote trigger or Same pipeline event triggered as external)
 * @param {string[]} ignoreJobs Names of job that may be run on current event
 * @returns {ParentBuilds} Merged parent builds { "${pipelineId}": { jobs: { "${jobName}": ${buildId} }, eventId: 123 }  }
```

File: plugins/builds/triggers/helpers.js (hunk 2 above)
Comment (yakanechi) [reply plugins/builds/triggers/helpers.js]: I fixed it!

File: plugins/builds/triggers/helpers.js (hunk 1 above)
Comment (yakanechi) [reply plugins/builds/triggers/helpers.js]: I fixed it!

File: plugins/builds/triggers/helpers.js [hunk 4]
```diff
@@ -1032,6 +1034,44 @@ function buildsToRestartFilter(joinPipeline, groupEventBuilds, currentEvent, cur
...
+
+    const visiting = [start];
+
+    const visited = new Set(visiting);
+
+    if (edges.length) {
+        while (visiting.length) {
+            const cur = visiting.pop();
+
+            edges.forEach(e => {
```
[the remark this answers is not in the document]
Comment (yakanechi) [reply plugins/builds/triggers/helpers.js]: As you pointed out, there were many unnecessary loops, so I reduced them.

**Review by y-oksaku — APPROVED** [review]
We might need to consider excluding a disabled job from subsequent jobs.
(Some users disable a job to skip executing in a restart event.)

**Comment by yakanechi** [comment]
All fixes have been done.
The following fixes will be made in a new PR

> We might need to consider excluding a disabled job from subsequent jobs.
> (Some users disable a job to skip executing in a restart event.)

File: plugins/builds/triggers/helpers.js [hunk 5]
```diff
@@ -668,6 +668,65 @@ async function getParallelBuilds({ eventFactory, parentEventId, pipelineId }) {
...
 
+/**
+ * Get subsequent job names which the root is the start from node
+ * @param   {Array}   [workflowGraph]         Array of graph vertices
+ * @param   {Array}   [workflowGraph.nodes]   Array of graph vertices
+ * @param   {Array}   [workflowGraph.edges]   Array of graph edges
+ * @param   {String}  [startNode]            Starting/trigger node
+ * @returns {Array<String>}                   subsequent job names
+ */
+function subsequentJobFilter(workflowGraph, startNode) {
```
Comment (tkyi) [inline plugins/builds/triggers/helpers.js:679]: I don't feel strongly but would something like `getDownstreamJobs` or `getSubsequentJobs` be more clear?

File: plugins/builds/triggers/helpers.js [hunk 6]
```diff
@@ -668,6 +668,65 @@ async function getParallelBuilds({ eventFactory, parentEventId, pipelineId }) {
...
+    const { nodes, edges } = workflowGraph;
+
+    if (!nodes.length) {
+        return [];
+    }
+
```
Comment (tkyi) [inline plugins/builds/triggers/helpers.js:685]: can probably remove these lines since the next if statement covers the same scenario
```suggestion
```

File: plugins/builds/triggers/helpers.js (hunk 5 above)
Comment (yakanechi) [reply plugins/builds/triggers/helpers.js]: @tkyi 
Thanks for your comment.
Renamed to"getSubsequentJobs" because it is used not only for dosntream but also for normal events.
